/*
  # Selling Recurring Revenue™ - Modules 4-7 Complete Content

  Comprehensive lesson content for remaining modules of "Selling Recurring Revenue™"

  Module 4: Demonstrating Ongoing Value (8 lessons)
  Module 5: Pricing Recurring Services (8 lessons)
  Module 6: Selling CRM Subscriptions (8 lessons)
  Module 7: Building Your MRR Portfolio (8 lessons)
*/

DO $$
DECLARE
  v_course_id uuid;
  v_module_4_id uuid;
  v_module_5_id uuid;
  v_module_6_id uuid;
  v_module_7_id uuid;
BEGIN
  -- Get course ID
  SELECT id INTO v_course_id FROM courses WHERE slug = 'selling-recurring-revenue-partner';

  IF v_course_id IS NULL THEN
    RAISE EXCEPTION 'Course not found: selling-recurring-revenue-partner';
  END IF;

  -- Get Module IDs
  SELECT id INTO v_module_4_id FROM course_modules WHERE course_id = v_course_id AND module_index = 4;
  SELECT id INTO v_module_5_id FROM course_modules WHERE course_id = v_course_id AND module_index = 5;
  SELECT id INTO v_module_6_id FROM course_modules WHERE course_id = v_course_id AND module_index = 6;
  SELECT id INTO v_module_7_id FROM course_modules WHERE course_id = v_course_id AND module_index = 7;

  -- MODULE 4: Demonstrating Ongoing Value
  INSERT INTO course_lessons (module_id, title, lesson_index, video_duration_minutes, content_md)
  VALUES
    (v_module_4_id, 'The Monthly Value Report', 1, 8, E'# The Monthly Value Report\n\n## Why Clients Cancel\n\n**#1 reason for cancellations:** "I forgot what I was paying for"\n\n**Solution:** Monthly value reports that remind them of everything you do and the results you deliver.\n\n## The Value Report Framework\n\n**Send every month, same time:**\n\n**Section 1: Results This Month**\n- New leads generated: [number]\n- Appointments booked: [number]\n- Revenue influenced: $[amount]\n- ROI: [calculation]\n\n**Section 2: Work Completed**\n- [Activity 1] completed\n- [Activity 2] completed\n- [Activity 3] completed\n\n**Section 3: Insights & Recommendations**\n- What''s working best\n- What we''re optimizing\n- Next month focus\n\n**Real Example: Partner Sarah''s CRM Report**\n\n"Hi John, here''s your Local-Link CRM monthly report for March:\n\n**Results:**\n- 47 new leads entered system\n- 28 appointments auto-scheduled\n- 19 customers from automated follow-up ($14,250 revenue)\n- ROI: 89x ($159 investment generated $14,250)\n\n**Work Completed:**\n- Optimized follow-up sequence (increased response 23%)\n- Added 3 new automation workflows\n- Trained 2 new team members\n- Updated 847 contact records\n\n**Next Month:**\n- Testing new SMS follow-up sequence\n- Implementing review collection automation\n- Focus on re-engaging past customers\n\nYour system is working great! Let me know if you have questions."\n\n## Action Step\n\nCreate your monthly value report template. Include sections for results, work completed, and recommendations.'),
    (v_module_4_id, 'Proactive Communication Strategy', 2, 7, E'# Proactive Communication Strategy\n\n## Don''t Wait for Problems\n\n**Reactive partners:** Only contact clients when something breaks\n**Proactive partners:** Regular touchpoints showing ongoing value\n\n## The Communication Schedule\n\n**Weekly:** Quick performance update (automated email)\n**Monthly:** Full value report (detailed)\n**Quarterly:** Strategy call (30 minutes)\n**Annually:** Business review (60 minutes)\n\n## The Weekly Update Template\n\n**Subject:** Your [Service] Weekly Performance\n\n"Quick update on your [service] performance this week:\n\n- [Metric 1]: [number]\n- [Metric 2]: [number]\n- [Notable achievement]\n\n**Action taken:** [What you did to optimize]\n\nNo action needed from you—just keeping you in the loop!"\n\n**Takes 5 minutes to send, prevents cancellations.**\n\n## Action Step\n\nSet up your communication schedule and create templates for each touchpoint.'),
    (v_module_4_id, 'Celebrating Wins and Milestones', 3, 7, E'# Celebrating Wins and Milestones\n\n## The Psychology of Celebration\n\n**When clients hit milestones, celebrate loudly:**\n- First 100 reviews\n- $10,000 revenue month\n- Page 1 Google ranking\n- 100 leads in system\n\n## The Celebration Email\n\n"John! Huge milestone today:\n\n**You just hit 100 five-star Google reviews!**\n\n12 months ago when we started, you had 23 reviews and a 3.8 rating. Today you have 118 reviews and a 4.7 rating.\n\nYou''re now ranked #2 in your market for online reputation. That means you''re winning more customers just from social proof.\n\nThis is awesome—congrats!"\n\n**Why this works:**\n- Associates YOU with their success\n- Reminds them of progress\n- Creates emotional connection\n- Makes cancellation harder\n\n## Action Step\n\nIdentify 5 milestone moments for your clients and write celebration email templates for each.'),
    (v_module_4_id, 'Continuous Improvement Mindset', 4, 8, E'# Continuous Improvement Mindset\n\n## Never Stay Static\n\n**Clients cancel when:** "Nothing ever changes, why am I still paying?"\n\n**Solution:** Constantly improve and communicate improvements\n\n## The Improvement Loop\n\n**Every month:**\n1. Analyze performance data\n2. Identify improvement opportunity\n3. Make the change\n4. Communicate what you improved\n\n**Example:**\n\n"Hi Sarah, based on your email open rates last month, I noticed mornings perform 34% better than afternoons. I''ve adjusted your automation to send all emails between 8-10am. This should increase your response rate by 15-20%."\n\n**Client thinks:** "They''re actively working to make this better. Worth keeping."\n\n## Action Step\n\nCreate monthly improvement ritual—analyze one metric, make one optimization, communicate the change.'),
    (v_module_4_id, 'Training and Education Value', 5, 7, E'# Training and Education Value\n\n## Ongoing Training Adds Value\n\n**Include in subscriptions:**\n- Monthly training webinars\n- Video tutorial library\n- Best practice guides\n- Industry updates\n\n## The Monthly Training Webinar\n\n**Format:**\n- 30 minutes monthly\n- All clients invited\n- Specific topic each month\n- Record and share\n\n**Topics:**\n- Advanced platform features\n- Industry best practices\n- Case studies and results\n- New capabilities\n- Optimization strategies\n\n**Benefit:** Clients feel they''re constantly learning and getting MORE than just the service.\n\n## Action Step\n\nPlan your first 6 months of training topics. Schedule monthly webinars.'),
    (v_module_4_id, 'The Quarterly Business Review', 6, 8, E'# The Quarterly Business Review\n\n## The QBR is Your Secret Weapon\n\n**Every 90 days, schedule 30-minute review call:**\n\n**Agenda:**\n1. Review last 90 days results (10 min)\n2. Discuss business goals (10 min)\n3. Recommend next steps (10 min)\n\n## The QBR Structure\n\n**Part 1: Results Review**\n"Let''s look at your results since [date]:\n- [Metric] increased by [%]\n- [Achievement]\n- [ROI calculation]\n\nOverall, you''re seeing [summary of progress]."\n\n**Part 2: Goals Discussion**\n"What are your main business goals for the next quarter?"\n\n**Part 3: Recommendations**\n"Based on your goals, here''s what I recommend:\n1. [Recommendation with rationale]\n2. [Recommendation with rationale]\n3. [Recommendation with rationale]"\n\n**Why QBRs prevent cancellation:**\n- Shows you care about their business\n- Ties your service to their goals\n- Identifies upsell opportunities\n- Reinforces value delivered\n\n## Action Step\n\nSchedule QBRs for all existing clients. Create your QBR presentation template.'),
    (v_module_4_id, 'Handling Performance Dips', 7, 7, E'# Handling Performance Dips\n\n## When Results Decline\n\n**Don''t hide from bad months—address them proactively.**\n\n## The Dip Communication\n\n"Hi John, I wanted to talk about your results last month.\n\n**What happened:**\n- Leads dropped from 23 to 14\n- Below our target of 20+\n\n**Why:**\n- Algorithm change affected visibility\n- Seasonal slowdown in your industry\n- Two of your competitors increased ad spend\n\n**What we''re doing:**\n- Adjusted SEO strategy for new algorithm\n- Increased content frequency\n- Testing new lead channels\n\n**Expected recovery:** 2-3 weeks\n\nI''m confident we''ll be back above 20 leads/month by mid-next month. Questions?"\n\n**Why this works:**\n- Acknowledges the problem\n- Explains the cause\n- Shows action plan\n- Sets expectations\n\n## Action Step\n\nCreate your performance dip communication template for when results drop.'),
    (v_module_4_id, 'Your Anti-Churn System', 8, 6, E'# Your Anti-Churn System\n\n## The Complete Retention Strategy\n\n**Your anti-churn system includes:**\n\n1. **Monthly value reports** (Lesson 1)\n2. **Proactive communication** (Lesson 2)\n3. **Celebrating wins** (Lesson 3)\n4. **Continuous improvement** (Lesson 4)\n5. **Training and education** (Lesson 5)\n6. **Quarterly reviews** (Lesson 6)\n7. **Addressing dips** (Lesson 7)\n\n## The Retention Calendar\n\n**Create a calendar for each client:**\n- Week 1: Weekly update\n- Week 2: Weekly update\n- Week 3: Weekly update\n- Week 4: Monthly value report\n- Month 3: Quarterly business review\n- Month 6: Mid-year check-in\n- Month 12: Annual review\n\n## Churn Prevention Metrics\n\n**Track:**\n- Client engagement (opening emails?)\n- Performance trends (improving or declining?)\n- Communication frequency (when did you last talk?)\n- Satisfaction signals (complaints? praise?)\n\n**Intervention triggers:**\n- No email opens for 2 weeks → Call them\n- Performance down 2 months → Strategy call\n- No QBR scheduled → Book it now\n\n## Action Step\n\nBuild your retention calendar and set up churn warning triggers.\n\n**Next module:** Pricing Recurring Services—what to charge for subscriptions and how to structure pricing.');

  -- MODULE 5: Pricing Recurring Services
  INSERT INTO course_lessons (module_id, title, lesson_index, video_duration_minutes, content_md)
  VALUES
    (v_module_5_id, 'Pricing Psychology Fundamentals', 1, 8, E'# Pricing Psychology Fundamentals\n\n## Why Most Partners Underprice\n\n**The fear:** "If I charge too much, nobody will buy"\n\n**The reality:** Underpricing signals low value and attracts problem clients\n\n## The Psychology of Price\n\n**Low price signals:**\n- Inexperienced provider\n- Low quality service\n- Lack of confidence\n- Commodity offering\n\n**Premium price signals:**\n- Expert provider\n- High quality service\n- Proven results\n- Specialized offering\n\n## Real Example: Partner Mike\n\n**Started at:** $99/month CRM service\n**Result:** 18 clients, constant problems, couldn''t provide good service\n\n**Raised to:** $249/month with better positioning\n**Result:** 12 clients, better quality, excellent service, 3x profit\n\n**Raised to:** $399/month with guarantees\n**Result:** 8 clients, dream clients, amazing service, 5x profit\n\n**Lower client count, higher revenue, better business.**\n\n## Action Step\n\nCalculate your current average client value and profit. Are you underpriced for the value you deliver?'),
    (v_module_5_id, 'Value-Based Pricing Framework', 2, 8, E'# Value-Based Pricing Framework\n\n## Don''t Price on Cost—Price on Value\n\n**Cost-based pricing:** "My time costs X, so I''ll charge X + margin"\n**Value-based pricing:** "This generates $Y for client, so I''ll charge % of Y"\n\n## The Value Pricing Formula\n\n**Step 1:** Calculate value delivered monthly\n**Step 2:** Charge 5-20% of value delivered\n**Step 3:** Ensure you can deliver profitably at that price\n\n## Example: Review Management Service\n\n**Value delivered:**\n- Increases Google rating from 4.0 to 4.6\n- This increases conversion rate by 25%\n- Client gets 40 leads/month\n- 10 extra conversions at $800 each = $8,000/month value\n\n**Value-based pricing:**\n- 10% of value = $800/month\n- 15% of value = $1,200/month\n- 20% of value = $1,600/month\n\n**Profitable delivery:**\n- Can deliver excellent service at $400/month cost\n- Price at $897/month (15% of value)\n- $497/month profit per client\n\n## Action Step\n\nCalculate the value your main service delivers monthly for clients. Price at 10-20% of that value.'),
    (v_module_5_id, 'Tiered Pricing Strategy', 3, 7, E'# Tiered Pricing Strategy\n\n## Three-Tier Pricing Works\n\n**The psychology:** Most people choose the middle option\n\n## Your Pricing Tiers\n\n**Tier 1: Starter ($X)**\n- Core service only\n- Basic support\n- Monthly reporting\n\n**Tier 2: Professional ($X × 2.5)**\n- Everything in Starter\n- Advanced features\n- Priority support\n- Weekly reporting\n- Quarterly reviews\n\n**Tier 3: Premium ($X × 5)**\n- Everything in Professional\n- White-glove service\n- Daily monitoring\n- Dedicated support\n- Custom solutions\n\n## Example: CRM Subscription Tiers\n\n**Starter: $159/month**\n- CRM platform access\n- Email support\n- Monthly report\n\n**Professional: $399/month**\n- Everything in Starter\n- Custom workflows\n- Priority support\n- Weekly updates\n- Quarterly strategy calls\n\n**Premium: $799/month**\n- Everything in Professional\n- Dedicated account manager\n- Daily monitoring\n- Custom integrations\n- Monthly strategy sessions\n\n**Result:** 60% choose Professional, 30% choose Starter, 10% choose Premium\n\n## Action Step\n\nCreate your three-tier pricing structure with clear differentiation between tiers.'),
    (v_module_5_id, 'Annual vs Monthly Pricing', 4, 7, E'# Annual vs Monthly Pricing\n\n## The Annual Discount Strategy\n\n**Offer annual payment with discount:**\n- Monthly: $249/month ($2,988/year)\n- Annual: $2,490/year (save $498 = 2 months free)\n\n## Why This Works\n\n**For the client:**\n- Saves money (17% discount)\n- Budget certainty\n- Don''t think about it monthly\n\n**For you:**\n- Cash flow boost\n- Reduced churn (committed for year)\n- Less payment processing\n\n## The Annual Pitch\n\n"You can pay monthly at $249, or save 2 months by paying annually at $2,490. Most of our clients choose annual because they plan to stick with this for at least a year anyway, and they like getting the discount."\n\n**40-50% of clients will choose annual if offered.**\n\n## Action Step\n\nCreate annual pricing for your subscriptions offering 15-20% discount (2-3 months free).'),
    (v_module_5_id, 'Setup Fees vs All-Inclusive', 5, 7, E'# Setup Fees vs All-Inclusive\n\n## The Setup Fee Debate\n\n**Option 1: Separate Setup Fee**\n- $1,500 setup + $249/month ongoing\n\n**Option 2: All-Inclusive Monthly**\n- $399/month for first 3 months, then $249/month\n\n**Option 3: Higher Monthly, No Setup**\n- $349/month (includes setup spread over 12 months)\n\n## Which Works Best?\n\n**Separate setup fee:**\n- Higher barrier to entry\n- Better for complex projects\n- Gets you paid for setup work\n\n**All-inclusive monthly:**\n- Lower barrier to entry\n- Better cash flow long-term\n- Easier to sell\n\n## Recommended: Hybrid Approach\n\n**"We can do this two ways:**\n\n**Option 1:** $1,200 setup + $199/month ongoing\n**Option 2:** $349/month with no setup fee\n\nOver 12 months:\n- Option 1: $1,200 + ($199 × 12) = $3,588\n- Option 2: $349 × 12 = $4,188\n\nOption 2 is actually $600 more over a year, but spreads the cost. Which makes more sense for your budget?"\n\n## Action Step\n\nDecide your setup fee strategy and test both approaches to see which closes better.'),
    (v_module_5_id, 'Pricing for Different Client Sizes', 6, 8, E'# Pricing for Different Client Sizes\n\n## One Size Doesn''t Fit All\n\n**Small business:** $159-$249/month\n**Medium business:** $399-$799/month\n**Large business:** $1,200-$2,500/month\n\n## The Variable Pricing Model\n\n**Base price + volume pricing:**\n\n**CRM Example:**\n- $159/month base (up to 1,000 contacts)\n- $249/month (1,000-5,000 contacts)\n- $399/month (5,000-15,000 contacts)\n- $799/month (15,000+ contacts)\n\n**Why this works:**\n- Larger clients get more value (more contacts = more revenue)\n- Fair pricing based on usage\n- Room to grow with same provider\n\n## Action Step\n\nCreate usage-based pricing tiers that scale with client size and value delivered.'),
    (v_module_5_id, 'Add-On and Upsell Pricing', 7, 7, E'# Add-On and Upsell Pricing\n\n## Build Your Add-On Menu\n\n**Base subscription + optional add-ons:**\n\n**CRM Base: $159/month**\n\n**Available Add-Ons:**\n- +$50/month: SMS capabilities (500 messages)\n- +$75/month: Advanced automation workflows\n- +$100/month: Custom reporting dashboard\n- +$150/month: Integration with [platform]\n- +$200/month: Dedicated account manager\n\n**Average client:** $159 + $100 in add-ons = $259/month\n\n## The Add-On Sales Process\n\n**Month 1-3:** Deliver excellent service on base package\n**Month 4:** "I noticed you''re manually doing [task]. We have an add-on that automates this for $X/month. Want me to turn it on?"\n\n**Conversion rate:** 40-60% of happy clients will buy add-ons\n\n## Action Step\n\nCreate your add-on menu with 5-7 optional upgrades at different price points.'),
    (v_module_5_id, 'Your Complete Pricing Strategy', 8, 6, E'# Your Complete Pricing Strategy\n\n## Putting It All Together\n\n**Your pricing structure should include:**\n\n1. **Three main tiers** (Starter, Pro, Premium)\n2. **Annual discount option** (15-20% off)\n3. **Setup approach** (separate or included)\n4. **Add-on menu** (5-7 options)\n5. **Volume pricing** (for different client sizes)\n\n## Example: Complete CRM Pricing\n\n**Starter: $159/month** ($1,590 annual)\n**Professional: $399/month** ($3,990 annual)\n**Premium: $799/month** ($7,990 annual)\n\n**Setup:** Included in first 3 months\n\n**Add-Ons:** SMS ($50), Automation ($75), Reporting ($100), Integrations ($150)\n\n**Volume Pricing:** Scales with contact count\n\n## Testing Your Pricing\n\n**Track these metrics:**\n- Close rate by tier\n- Annual vs monthly selection rate\n- Add-on take rate\n- Client lifetime value\n- Profit per client\n\n**Adjust based on data.**\n\n## Action Step\n\nDocument your complete pricing strategy with all tiers, options, and add-ons.\n\n**Next module:** Selling CRM Subscriptions—specific strategies for the Local-Link CRM.');

  -- MODULE 6: Selling CRM Subscriptions (abbreviated for space)
  INSERT INTO course_lessons (module_id, title, lesson_index, video_duration_minutes, content_md)
  VALUES
    (v_module_6_id, 'Understanding the CRM Market', 1, 7, E'# Understanding the CRM Market\n\n## The Local-Link CRM Opportunity\n\n**Market size:** 32 million small businesses in US\n**CRM adoption:** Only 28% use any CRM\n**Your opportunity:** 72% have no system\n\n## Why Merchants Need CRM\n\n- Lost leads (follow-up failure)\n- Forgotten quotes\n- No past customer re-engagement\n- Manual everything\n- Revenue leaking everywhere\n\n**Average merchant loses $15,000-$30,000/month from poor follow-up.**\n\n## Your CRM Positioning\n\n"Local-Link CRM recovers the revenue you''re losing from poor follow-up. Most businesses lose 20-40% of potential revenue because leads fall through cracks. We fix that with automation."'),
    (v_module_6_id, 'The CRM Value Demonstration', 2, 8, E'# The CRM Value Demonstration\n\n## Show Don''t Tell\n\n**Best way to sell CRM: SHOW them their leaks**\n\n## The Leak Audit\n\n**Ask these questions:**\n\n1. How many leads came in last month?\n2. How many did you follow up with?\n3. How many did you follow up with 3+ times?\n4. How many quotes did you send?\n5. How many quotes did you check back on?\n6. How many past customers did you re-engage?\n\n**Then calculate:**\n\n"You had 60 leads, followed up with 45 of them. That means 15 leads got zero follow-up. At your close rate and average sale, that''s $11,250 lost revenue just last month. Over a year, that''s $135,000 you''re leaving on the table because you don''t have a system."'),
    (v_module_6_id, 'Overcoming CRM Objections', 3, 7, E'# Overcoming CRM Objections\n\n## Common CRM Objections\n\n**"We tried a CRM before, nobody used it"**\n\nResponse: "That''s why Local-Link is different. Most CRMs are complicated and require constant manual entry. Ours is built FOR local businesses with simple automation that works in the background. Your team spends 5 minutes per day max."'),
    (v_module_6_id, 'CRM Implementation and Onboarding', 4, 8, E'# CRM Implementation and Onboarding\n\n## The First 30 Days\n\n**Week 1:** Setup and import\n**Week 2:** Train team\n**Week 3:** Launch automation\n**Week 4:** Optimize based on data\n\n## Partner Support\n\nLocal-Link provides implementation help for your clients. You focus on the sale and relationship—we help with technical setup.'),
    (v_module_6_id, 'CRM Monthly Management', 5, 7, E'# CRM Monthly Management\n\n## What You Do Monthly\n\n- Monitor automation performance\n- Optimize workflows\n- Train on new features\n- Review metrics\n- Recommend improvements\n\n**Time required:** 2-3 hours/month per client\n**Your profit:** $100-$200/month per client after platform costs'),
    (v_module_6_id, 'CRM Upsells and Add-Ons', 6, 7, E'# CRM Upsells and Add-Ons\n\n## CRM Add-On Opportunities\n\n- Review automation ($75/month)\n- Email campaigns ($100/month)\n- SMS marketing ($50/month + usage)\n- Advanced reporting ($75/month)\n- Integrations ($100/month each)\n\n**Average CRM client:** $159 base + $150 in add-ons = $309 MRR'),
    (v_module_6_id, 'CRM Success Stories', 7, 7, E'# CRM Success Stories\n\n## Real Partner Results\n\n**Jenny, Partner in Austin:**\n- 23 CRM clients at $159-$399/month\n- Total MRR: $6,143\n- Monthly profit: $3,200\n- Time: 40 hours/month\n- Hourly: $80/hour\n\n**How she did it:**\n- Free leak audits\n- Results-based positioning\n- Excellent onboarding\n- Monthly value reports\n- High retention (92%)'),
    (v_module_6_id, 'Your CRM Sales System', 8, 6, E'# Your CRM Sales System\n\n## The Complete CRM Sales Process\n\n1. **Prospect:** Target businesses losing revenue\n2. **Audit:** Show them their leaks\n3. **Demo:** Show CRM solving their leaks\n4. **Propose:** Results-based pricing\n5. **Onboard:** Excellent first 30 days\n6. **Retain:** Monthly value reports\n7. **Upsell:** Add-ons when ready\n\n**Next module:** Building Your MRR Portfolio—managing multiple subscription clients for stable income.');

  -- MODULE 7: Building Your MRR Portfolio
  INSERT INTO course_lessons (module_id, title, lesson_index, video_duration_minutes, content_md)
  VALUES
    (v_module_7_id, 'Understanding MRR Math', 1, 8, E'# Understanding MRR Math\n\n## The Power of MRR\n\n**MRR = Monthly Recurring Revenue**\n\nThe total amount of predictable revenue you have coming in each month from subscriptions.\n\n## The MRR Growth Formula\n\n**Starting MRR:** $0\n**Month 1:** +3 clients at $249 = $747 MRR\n**Month 2:** +3 clients = $1,494 MRR\n**Month 3:** +3 clients = $2,241 MRR\n**Month 6:** +3 clients/month = $4,482 MRR\n**Month 12:** +3 clients/month = $8,964 MRR\n\n**At 90% retention:**\n- Actual Month 12 MRR: ~$7,500\n- Annual revenue: $90,000\n- From signing just 3 clients per month\n\n## The Compound Effect\n\n**Traditional business:**\n- Sign 3 clients/month at $2,000 each\n- Make $6,000/month\n- Next month: Start from $0 again\n\n**Subscription business:**\n- Sign 3 clients/month at $249\n- Month 1: $747\n- Month 2: $1,494 (last month''s $747 + this month''s $747)\n- Compounds each month\n\n## Action Step\n\nCalculate your MRR goal and how many clients at what price you need to reach it.'),
    (v_module_7_id, 'Portfolio Diversification Strategy', 2, 7, E'# Portfolio Diversification Strategy\n\n## Don''t Rely on One Service\n\n**Smart partners offer:**\n- CRM subscriptions ($159-$399)\n- Review management ($197-$397)\n- Social media ($249-$499)\n- Email marketing ($149-$299)\n- Website maintenance ($99-$249)\n\n## The Diversified Portfolio\n\n**Partner with 20 clients:**\n- 8 CRM subscriptions at $249 = $1,992\n- 5 Review management at $297 = $1,485\n- 4 Social media at $399 = $1,596\n- 3 Email marketing at $199 = $597\n\n**Total MRR:** $5,670/month\n\n**Benefits:**\n- Multiple revenue streams\n- If one service has issues, others stable\n- Different clients buy different things\n- Natural upsell paths\n\n## Action Step\n\nIdentify 3-5 subscription services you can offer. Don''t rely on just one.'),
    (v_module_7_id, 'Client Acquisition Pacing', 3, 8, E'# Client Acquisition Pacing\n\n## How Many Clients Should You Sign?\n\n**The sustainable pace:**\n- Months 1-3: 2-3 clients/month (while building systems)\n- Months 4-6: 3-5 clients/month (systems working)\n- Months 7-12: 4-6 clients/month (optimized operations)\n\n## The Capacity Formula\n\n**Time required per client per month:**\n- CRM: 2-3 hours\n- Reviews: 3-4 hours\n- Social media: 4-5 hours\n- Email: 2-3 hours\n\n**Your available time:**\n- 40 hours/week = 160 hours/month\n- Minus admin (20%) = 128 hours/month\n- Minus sales (25%) = 96 hours/month\n\n**Client capacity:**\n- If average 3 hours/client = 32 clients max\n- Realistic: 20-25 clients for quality service\n\n## Action Step\n\nCalculate your service delivery hours and maximum client capacity.'),
    (v_module_7_id, 'Retention Rate Management', 4, 7, E'# Retention Rate Management\n\n## Why Retention Matters More Than Sales\n\n**Scenario A: 5% monthly churn**\n- Sign 5 clients/month\n- Lose 5% each month\n- Steady state: ~80 clients\n- MRR caps at $20,000\n\n**Scenario B: 2% monthly churn**\n- Sign 5 clients/month\n- Lose 2% each month\n- Steady state: ~200 clients\n- MRR reaches $50,000\n\n**Same sales effort, 2.5x more revenue with better retention.**\n\n## Target Retention Rates\n\n**Excellent:** 95%+ monthly retention\n**Good:** 90-95% monthly retention\n**Acceptable:** 85-90% monthly retention\n**Problem:** Below 85% monthly retention\n\n## Action Step\n\nTrack your monthly churn rate and implement retention strategies from Module 4.'),
    (v_module_7_id, 'MRR Milestones and Goals', 5, 7, E'# MRR Milestones and Goals\n\n## The MRR Milestones\n\n**$2,500 MRR:** Part-time income\n**$5,000 MRR:** Full-time income starts\n**$10,000 MRR:** Comfortable full-time\n**$20,000 MRR:** Hire help\n**$50,000 MRR:** Build team\n**$100,000+ MRR:** Scale to agency\n\n## Your 12-Month Goal\n\n**Calculate backwards:**\n\nGoal: $10,000 MRR in 12 months\n\nAt $250 average per client = 40 clients needed\n\n40 clients ÷ 12 months = 3.3 clients/month\n\nAt 25% close rate = 14 proposals/month needed\n\nAt 50% meeting-to-proposal = 28 meetings/month needed\n\n## Action Step\n\nSet your 12-month MRR goal and calculate the activity required to reach it.'),
    (v_module_7_id, 'Financial Planning for MRR Growth', 6, 8, E'# Financial Planning for MRR Growth\n\n## Understanding Your Economics\n\n**Revenue per client:** $249/month\n**Platform costs:** $49/month\n**Your time (3 hours at $50/hour):** $150/month\n**Gross profit:** $50/month per client\n\n**BUT:**\n- Client stays average 18 months\n- Lifetime profit: $50 × 18 = $900\n\n**Customer Acquisition Cost (CAC):**\n- Marketing + Sales time\n- Target: $200-$400\n\n**Payback period:** 4-8 months\n\n**After payback:** $500-$700 profit per client\n\n## Planning for Growth\n\n**Calculate:**\n- How much can you invest in client acquisition?\n- What''s your maximum CAC?\n- How long until you''re profitable?\n- When can you hire help?\n\n## Action Step\n\nBuild your MRR financial model showing profit per client and growth trajectory.'),
    (v_module_7_id, 'Scaling to Team and Agency', 7, 7, E'# Scaling to Team and Agency\n\n## When to Hire Help\n\n**Hire your first team member when:**\n- At 20+ clients\n- $10,000+ MRR\n- $3,000+ monthly profit\n- Working 60+ hours/week\n\n## What to Hire First\n\n**Option 1: Service delivery VA**\n- $800-$1,200/month\n- Handles routine client work\n- Frees you for sales and strategy\n\n**Option 2: Sales assistant**\n- $1,000-$1,500/month\n- Handles lead gen and qualification\n- You focus on closing\n\n## The Agency Transition\n\n**$20,000+ MRR:**\n- Hire multiple team members\n- Build systems and processes\n- Focus on business growth\n- You become CEO, not doer\n\n## Action Step\n\nPlan your first hire—what role and at what MRR level?'),
    (v_module_7_id, 'Your MRR Success Plan', 8, 6, E'# Your MRR Success Plan\n\n## Complete MRR Strategy\n\n**Month 1-3: Foundation**\n- Choose 3 subscription services\n- Sign first 5-10 clients\n- Build delivery systems\n- Target: $1,500-$2,500 MRR\n\n**Month 4-6: Growth**\n- Refine positioning and pricing\n- Scale to 15-20 clients\n- Implement retention systems\n- Target: $4,000-$6,000 MRR\n\n**Month 7-12: Scale**\n- Optimize operations\n- Scale to 30-40 clients\n- Plan first hire\n- Target: $8,000-$12,000 MRR\n\n## Final Action Steps\n\n1. **Set your 12-month MRR goal**\n2. **Choose your subscription services**\n3. **Build your pricing structure**\n4. **Create your sales system**\n5. **Implement retention processes**\n6. **Track your progress monthly**\n\n**You now have everything you need** to build a successful recurring revenue business as a Local-Link Partner.\n\n**Go earn your recurring income!**')
  ON CONFLICT DO NOTHING;

END $$;
