/*
  # Seed DFY Products - Simplified

  Seeds 14 DFY products with correct pricing and descriptions
*/

INSERT INTO public.dfy_products (slug, name, category, short_value_prop, long_description, outcomes, includes, faq, setup_sla_hours, setup_price_cents, monthly_price_cents)
VALUES
('ai-missed-call-booking', 'AI Missed-Call Text Back + Booking', 'lead_capture', 'Miss a call? AI texts back instantly and books the job.', 'When a customer calls and you miss it, this system automatically texts them back, answers questions, and pushes them to book or request a quote. We set it up for your business and keep it running.', '["Recover missed leads automatically","Book more jobs without hiring staff","Faster response time than competitors"]', '["AI texting workflow configured for your services","Lead capture + booking prompts","Support + monitoring included","Opt-out compliant messaging"]', '[{"q":"Do I need new software?","a":"No. We integrate with what you already use whenever possible."},{"q":"How fast can this go live?","a":"Typically within 24–72 hours after intake."}]', 48, 29700, 9700),
('ai-website-chat-closer', 'AI Website Chat Closer', 'lead_capture', 'Turn website visitors into booked appointments 24/7.', 'We install an AI chat assistant that answers FAQs, qualifies leads, and books appointments or captures lead info. You get more conversions from the traffic you already have.', '["Convert more site visitors into leads","Answer FAQs instantly 24/7","Book appointments automatically"]', '["Chat widget installed on your site","AI trained on your services + FAQs","Booking/lead capture flow","Reporting + support"]', '[{"q":"Will it match my brand voice?","a":"Yes. We tune tone and responses during setup."}]', 72, 34700, 9700),
('ai-social-dm-autoresponder', 'AI Social DM Auto-Responder (FB + IG)', 'lead_capture', 'Instantly reply to DMs and turn messages into bookings.', 'We connect AI to your Facebook/Instagram messaging so leads get instant answers, qualification, and a booking link—without you living in your inbox.', '["Reply instantly to every DM","Capture lead details automatically","Increase conversions from social"]', '["DM flows configured for FAQs + offers","Lead capture + booking link routing","Support + monitoring","Opt-out compliant messaging"]', '[{"q":"Does it work with ads?","a":"Yes—great for DM-driven campaigns and click-to-message ads."}]', 72, 29700, 7900),
('ai-speed-to-lead-dialer', 'AI Speed-to-Lead Dialer', 'lead_capture', 'New lead comes in and AI calls them fast and books the job.', 'When a lead submits a form, AI calls them quickly, qualifies them, and books an appointment or routes the call to you. Speed-to-lead is one of the biggest conversion levers.', '["Call leads within minutes","Qualify + book automatically","Stop losing leads to faster competitors"]', '["Lead trigger + AI call flow","Qualification questions","Booking/transfer logic","Support + reporting"]', '[{"q":"Can it transfer hot leads to my phone?","a":"Yes—based on your routing rules."}]', 72, 39700, 12700),
('ai-marketing-funnels', 'AI-Powered Marketing Funnels (DFY)', 'funnels', 'A complete funnel that captures leads, follows up, and books appointments automatically.', 'We build your funnel end-to-end: landing page, lead capture, tracking, and AI follow-up by text/email that drives bookings. This is the anchor offer that makes everything else easier to sell.', '["Turn clicks into booked appointments","Automatic follow-up by text + email","Track conversions end-to-end"]', '["DFY landing page + thank you page","Lead form + tracking","AI follow-up sequences","Booking integration","Support + reporting"]', '[{"q":"Do I need ads?","a":"No. Funnels work with ads, SEO, referrals, and any traffic."}]', 72, 99700, 14700),
('ai-quote-generator', 'AI Quote Generator + Follow-Up', 'funnels', 'Send quotes fast and follow up automatically until they book.', 'We build a quoting flow that sends estimates based on your rules, then follows up automatically by text/email to win the job.', '["Send quotes instantly","Win more estimates with follow-up","Reduce time spent chasing leads"]', '["Quote rules configured","Quote delivery by SMS/email","Automatic follow-up sequences","Booking CTA + tracking"]', '[{"q":"Can it handle different services?","a":"Yes—pricing rules are configured during intake."}]', 72, 49700, 9700),
('ai-reactivation-engine', 'AI Customer Reactivation Engine', 'funnels', 'Upload your old customers and AI brings them back.', 'We run a reactivation campaign that texts/emails past customers and leads with an offer and booking link, then tracks conversions.', '["Bring back past customers","Fill the calendar without new ads","Automated follow-up until booking"]', '["List import + segmentation","AI messaging sequences","Offer + booking integration","Reporting dashboard"]', '[{"q":"Can you run this monthly?","a":"Yes—recurring campaigns can be scheduled."}]', 72, 39700, 9700),
('ai-review-booster', 'AI Review Booster + Protection', 'reviews', 'More 5-star reviews with unhappy feedback routed privately.', 'We automate review requests after jobs and protect your reputation by routing unhappy customers to private feedback before they post publicly.', '["Increase 5-star review volume","Reduce public negative reviews","Improve Google rankings over time"]', '["Automated review requests","Private feedback capture","Optional AI review responses","Support + monitoring"]', '[{"q":"Does this work with Google reviews?","a":"Yes—Google is supported."}]', 72, 24700, 7900),
('ai-gbp-manager', 'AI Google Business Profile Manager', 'reviews', 'Weekly GBP posting plus assistance to stay visible locally.', 'We keep your Google Business Profile active with consistent posts and help respond to reviews, improving local visibility.', '["Stay active on Google automatically","Improve local visibility signals","Save time on posting + responses"]', '["Weekly post automation","Response assistance rules","Light reporting + support"]', '[{"q":"Do you need access to my GBP?","a":"Yes during setup."}]', 72, 19700, 5900),
('ai-local-seo-pages', 'AI Local SEO Page Generator', 'visibility', 'Generate and publish city/service pages to rank in more towns.', 'We generate local SEO pages for your services and service areas and publish on a schedule to grow organic leads over time.', '["Rank in more towns","Publish consistently without writing","Build long-term organic lead flow"]', '["City/service page generation","Publishing schedule","Basic internal linking plan","Support + reporting"]', '[{"q":"What websites are supported?","a":"Most common platforms can be supported."}]', 72, 49700, 12700),
('ai-social-content-repurposer', 'AI Social Content Repurposer', 'visibility', 'Turn reviews, jobs, and FAQs into weekly posts automatically.', 'We set up a content engine that repurposes your real business inputs into social posts and Google updates—so you stay visible without doing content work.', '["Post consistently without effort","Use real business proof","Stay top-of-mind locally"]', '["Weekly post generator","Approval or auto-post options","Content themes configured","Support + monitoring"]', '[{"q":"Can I approve posts before they go out?","a":"Yes."}]', 72, 19700, 4900),
('ai-ad-copy-generator', 'AI Short-Form Ad Copy Generator', 'visibility', 'Weekly ad copy packs for offers, promos, and hiring.', 'We generate local ad copy packs you can use for Facebook/Instagram—based on your offer, service area, and brand voice.', '["Better ad copy faster","More tests = more winners","Stop guessing what to write"]', '["Weekly copy pack delivery","Offer/angle variations","Local targeting language","Support + revisions"]', '[{"q":"Do you run the ads too?","a":"No—ad management is available as an add-on."}]', 72, 9700, 3900),
('ai-upsell-engine', 'AI Upsell & Cross-Sell Engine', 'ops', 'Automatically upsell add-ons after every job.', 'After a job is completed, AI sends a smart follow-up offering relevant add-ons, seasonal services, or packages—driving more revenue per customer.', '["Increase average order value","Automate seasonal promotions","Turn one-time customers into repeat buyers"]', '["Post-job messaging automation","Upsell logic + offers","Booking/checkout routing","Support + reporting"]', '[{"q":"Can you tailor upsells by service type?","a":"Yes."}]', 72, 29700, 7900),
('ai-subscription-saver', 'AI Subscription Saver', 'ops', 'Save cancellations automatically with pause/downgrade offers.', 'If a customer cancels, AI follows up with save offers and tracks saves—protecting recurring revenue.', '["Reduce churn automatically","Recover cancellations","Increase lifetime value"]', '["Cancellation-trigger workflows","Save offers configured","Outcome tracking","Support + monitoring"]', '[{"q":"Do I need a subscription business?","a":"It works best for recurring services."}]', 72, 24700, 6700)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  short_value_prop = EXCLUDED.short_value_prop,
  long_description = EXCLUDED.long_description,
  outcomes = EXCLUDED.outcomes,
  includes = EXCLUDED.includes,
  faq = EXCLUDED.faq,
  setup_sla_hours = EXCLUDED.setup_sla_hours,
  setup_price_cents = EXCLUDED.setup_price_cents,
  monthly_price_cents = EXCLUDED.monthly_price_cents,
  is_active = EXCLUDED.is_active;