/*
  # Add Selling Recurring Revenue™ Course - Modules 3-5

  Adds remaining course content:
  - Module 3: Sales System & Pipeline (5 lessons)
  - Module 4: Objections, Retention, Expansion (5 lessons)
  - Module 5: Delivery, Automation, Scaling (5 lessons)
*/

DO $$
DECLARE
  v_course_id uuid;
  v_mod3 uuid;
  v_mod4 uuid;
  v_mod5 uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'selling-recurring-revenue';
  
  IF v_course_id IS NULL THEN
    RAISE EXCEPTION 'Course not found';
  END IF;

  -- Module 3: Sales System & Pipeline
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 3, 'Sales System & Pipeline', 'Weekly cadence, prospecting, discovery, pricing, and closing.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title
  RETURNING id INTO v_mod3;

  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes) VALUES
    (v_mod3, 1, 'Your Weekly MRR Sales Rhythm', E'# Your Weekly MRR Sales Rhythm\n\n## Overview\nA repeatable weekly operating system that predictably generates recurring revenue.\n\n## Key KPIs\n- **Conversations**: New contacts made\n- **Appointments**: Scheduled discovery calls\n- **Shows**: Appointments that actually happen\n- **Closes**: Signed agreements\n- **Onboards**: Activated clients\n\n## Weekly Numbers Example\nTo close 4 clients/month at $297/mo:\n- 40 conversations/week\n- 8 appointments/week\n- 6 shows/week\n- 4 closes/month\n\n## Exercise\nSet weekly numbers for your first 10 clients. Work backwards from your revenue goal.', 20),
    
    (v_mod3, 2, 'Prospecting Without Social Media', E'# Prospecting Without Social Media\n\n## Overview\nBuild targeted lists using proven local business directories without relying on social media algorithms.\n\n## Prospecting Sources\n- **Google Maps**: Search "[niche] near [city]"\n- **Local directories**: Chamber of Commerce, BBB, industry associations\n- **LinkedIn**: Company search by industry + location\n- **Yelp/Yellow Pages**: Category browsing\n- **Referrals**: From existing clients\n\n## Outreach Angles That Work\n1. "Noticed you don''t have a way to capture missed calls..."\n2. "Saw your reviews could use some help..."\n3. "Most [niche] owners lose $X/month to [problem]..."\n\n## Exercise\nCreate 50 leads and categorize by readiness:\n- **Hot**: Clear pain, ready now\n- **Warm**: Interested but timing uncertain\n- **Cold**: Need education first', 25),
    
    (v_mod3, 3, 'Discovery That Creates Urgency', E'# Discovery That Creates Urgency\n\n## Overview\nDiscovery questions that uncover the real cost of the problem and create natural urgency to solve it.\n\n## The Discovery Script\n\n1. **"What''s happening now?"**\n   - Let them describe the current situation\n\n2. **"How long has this been an issue?"**\n   - Establishes timeline and pain duration\n\n3. **"What does this cost you monthly?"**\n   - Quantify the problem in dollars\n\n4. **"What have you tried?"**\n   - Identify past failed solutions\n\n5. **"If this continues for 90 days, what happens?"**\n   - Create urgency through future-pacing\n\n6. **"Who makes the final decision?"**\n   - Identify decision maker and process\n\n## Exercise\nRole-play this script with a colleague or record yourself. Identify your weak points and practice until it feels natural.', 30),
    
    (v_mod3, 4, 'Presenting Pricing Like a Pro', E'# Presenting Pricing Like a Pro\n\n## Overview\nPresent 3 options and anchor to outcome, not tasks. Guide them to the right tier for their needs.\n\n## The 3-Option Presentation\n\n### Step 1: Recap the Pain\n"So you''re losing about $2,000/month to missed calls..."\n\n### Step 2: Present the Solution\n"We have 3 ways to solve this, depending on how hands-on you want to be..."\n\n### Step 3: Show the Tiers\n- **Option 1** (Starter): Self-serve, $147/mo\n- **Option 2** (Core): Done-with-you, $297/mo ⭐ (anchor here)\n- **Option 3** (Premium): Done-for-you, $597/mo\n\n### Step 4: Ask\n"Which approach feels right for where you are?"\n\n## Key Rules\n- Talk about outcomes, not features\n- Use monthly language ("investment" not "fee")\n- Pause after presenting price\n- Don''t negotiate on first call\n\n## Exercise\nWrite your 3-tier pitch and practice it. Record yourself and self-review using the checklist provided.', 25),
    
    (v_mod3, 5, 'Closing & Next Steps', E'# Closing & Next Steps\n\n## Overview\nUse a start-date close and a clean onboarding handoff to reduce buyer''s remorse and create momentum.\n\n## The Start-Date Close\n\n"So if we get started this week, here''s what happens:\n- **Day 1-2**: We gather your assets and set up access\n- **Day 3-5**: System goes live, first automation running\n- **Day 7**: First results, quick win report\n\nWhen would you like to start - this Thursday or Monday?"\n\n## Handling "I Need to Think"\n\n"Totally understand. What specifically do you need to think about?"\n\n(Listen, then address the real objection)\n\n## The Next Steps Email Template\n\n**Subject**: Your [Solution] Start Date: [Date]\n\n**Body**:\n- Confirm start date\n- What we need from you\n- Next call scheduled\n- Expected Week 1 wins\n- Payment link\n\n## Exercise\nWrite your start-date close script and next steps email. Test with next 3 prospects.', 20)
  ON CONFLICT (module_id, lesson_index) DO NOTHING;

  -- Module 4: Objections, Retention, Expansion
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 4, 'Objections, Retention, Expansion', 'Handle objections, keep clients, expand accounts, reduce churn.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title
  RETURNING id INTO v_mod4;

  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes) VALUES
    (v_mod4, 1, 'The Big 6 Objections', E'# The Big 6 Objections\n\n## Overview\nFramework: **Clarify → Reframe → Prove → Ask**\n\n## Objection #1: "Too Expensive"\n\n**Clarify**: "Too expensive compared to what?"\n\n**Reframe**: "What''s it costing you now to NOT solve this?"\n\n**Prove**: Share case study or ROI calculation\n\n**Ask**: "If this paid for itself in 30 days, would that work?"\n\n## Objection #2: "I Need to Think"\n\n**Clarify**: "What specifically do you need to think about?"\n\n**Reframe**: Address the real concern (usually price, trust, or timing)\n\n**Prove**: Offer testimonial or guarantee\n\n**Ask**: "What would make this an easy yes?"\n\n## Objection #3: "Already Have Someone"\n\n**Clarify**: "How''s that working for you?"\n\n**Reframe**: "We don''t replace, we add..."\n\n**Prove**: Show what they''re missing\n\n**Ask**: "Would you be open to a 30-day test?"\n\n## Objection #4: "No Time"\n\n**Clarify**: "What takes most of your time now?"\n\n**Reframe**: "This actually saves you time by..."\n\n**Prove**: Show time saved\n\n**Ask**: "If this gave you back 5 hours/week, would that help?"\n\n## Objection #5: "Send Me Info"\n\n**Clarify**: "What specifically do you want to see?"\n\n**Reframe**: "I can send that, but let me ask..."\n\n**Prove**: (Address real concern)\n\n**Ask**: "If the info looks good, when would you start?"\n\n## Objection #6: "Need Partner Approval"\n\n**Clarify**: "What concerns will they have?"\n\n**Reframe**: "Let''s make sure you have everything to present this properly..."\n\n**Prove**: Provide one-page ROI summary\n\n**Ask**: "Want to bring them on our next call?"\n\n## Exercise\nWrite one response per objection using the framework. Practice with a partner.', 30),
    
    (v_mod4, 2, 'Handling Price & Budget', E'# Handling Price & Budget\n\n## Overview\nUse ROI framing and smaller tier entry to overcome price objections without discounting.\n\n## ROI Framing Script\n\n"I get it. $297/mo feels like a lot. Let me show you something...\n\nYou said you lose about 5 calls per week at $500 average job value. That''s $2,500/week in missed revenue.\n\nIf we capture just 20% of those, that''s $500/week = $2,000/month in found revenue.\n\nOur system costs $297. So you net $1,700/month. And that''s conservative.\n\nDoes that math make sense?"\n\n## The Smaller Tier Entry\n\n"I hear you on budget. Let''s start with the Starter tier at $147. Get results in 30 days, then upgrade if you want more."\n\n## The ROI Mini-Calculator Template\n\n| Problem Metric | Your Number | Monthly Cost |\n|----------------|-------------|-------------|\n| Missed calls/week | _____ | $_____ |\n| Lost jobs/month | _____ | $_____ |\n| **Total Cost** | | **$_____** |\n\n| Our Solution | Cost | Net Benefit |\n|--------------|------|-------------|\n| Capture 20% more | $297/mo | $_____ |\n\n## Exercise\nCreate an ROI mini-calculator for your niche. Test with 3 prospects.', 20),
    
    (v_mod4, 3, 'Retention Meetings & Reporting', E'# Retention Meetings & Reporting\n\n## Overview\nMonthly touchpoint agenda + win tracking that keeps clients engaged and prevents churn.\n\n## Monthly Meeting Agenda (15-20 min)\n\n### 1. Wins (5 min)\n"Here''s what happened this month..."\n- New leads captured\n- Reviews received\n- Calls answered\n- Revenue impact estimate\n\n### 2. Performance Review (5 min)\n- Show metrics dashboard\n- Compare to last month\n- Highlight trends\n\n### 3. What We Did (3 min)\n- List activities completed\n- Show system is working\n\n### 4. Next Month Plan (3 min)\n- What we''re optimizing\n- Any new features/add-ons\n\n### 5. Questions & Expansion (4 min)\n- "Any concerns?"\n- "Ready to add [next tier/feature]?"\n\n## The 1-Page Monthly Report Template\n\n**[Client Name] - [Month] Performance Report**\n\n**Wins This Month:**\n- ✅ [Win 1]\n- ✅ [Win 2]\n- ✅ [Win 3]\n\n**Key Metrics:**\n- Metric 1: [number] (↑ X% from last month)\n- Metric 2: [number]\n- Metric 3: [number]\n\n**What We Did:**\n- [Activity 1]\n- [Activity 2]\n- [Activity 3]\n\n**Next Steps:**\n- [Action 1]\n- [Action 2]\n- Recommended: [Upsell opportunity]\n\n**Questions?** Reply to this email or call [number]\n\n## Exercise\nCreate your monthly report template and schedule all client monthly meetings in your calendar.', 25),
    
    (v_mod4, 4, 'Upsells & Cross-Sells', E'# Upsells & Cross-Sells\n\n## Overview\nExpansion triggers and timing - when and how to offer add-ons without feeling pushy.\n\n## 10 Expansion Triggers\n\n1. **90 days in**, results proven → offer next tier\n2. **Missed call volume increasing** → offer AI receptionist\n3. **Low review count** → offer review automation\n4. **No-show appointments** → offer reminder system\n5. **Repeat customer request** → offer loyalty program\n6. **Social media questions** → offer social posting\n7. **Hiring needs** → offer recruiting tools\n8. **Slow season coming** → offer promotional campaigns\n9. **Competitor pressure** → offer reputation management\n10. **Celebrating wins** → offer done-for-you upgrade\n\n## The Expansion Script\n\n"Hey [Name], quick question...\n\nI noticed [trigger]. A lot of our clients in [niche] add [solution] at this stage and see [outcome].\n\nIt''s an extra $[price]/mo and takes about 20 minutes to set up.\n\nWant me to show you how it works on our next call?"\n\n## Expansion Playbook Template\n\n| Trigger | Solution | Price | ROI Pitch |\n|---------|----------|-------|----------|\n| [Trigger] | [Add-on] | $X/mo | [Benefit] |\n\n## Exercise\nList 10 triggers that justify upsells for your niche. Write expansion scripts for your top 3 add-ons.', 20),
    
    (v_mod4, 5, 'Churn Prevention & Recovery', E'# Churn Prevention & Recovery\n\n## Overview\nEarly warning signals + rescue scripts to save clients before they cancel.\n\n## 5 Churn Warning Signals\n\n1. **Skipped monthly meeting** 2x in a row\n2. **Not using the system** (low activity)\n3. **Short, terse email responses**\n4. **"We need to talk about cost"**\n5. **Request to pause or downgrade**\n\n## Churn Prevention Actions\n\n- **Signal detected** → immediate personal outreach\n- **Proactive check-in**: "Everything OK?"\n- **Show recent wins**: "Did you see..."\n- **Offer free optimization**: "Let me help you get more from this..."\n- **Executive attention**: Escalate to senior person\n\n## Rescue Message #1: Inactive Client\n\n**Subject**: [Client Name] - Quick Check-In\n\n"Hey [Name],\n\nNoticed you haven''t been using [system] much lately. Everything OK?\n\nLet''s jump on a quick call this week. I''ll show you a few tweaks that could make a big difference.\n\nWhen works for you?"\n\n## Rescue Message #2: Price Complaint\n\n**Subject**: Let''s Find a Solution\n\n"Hey [Name],\n\nI understand budget is tight right now. Let''s talk options:\n\n1. Pause for 30 days (stay active, no charge)\n2. Downgrade to Starter tier ($147 vs $297)\n3. Keep current, show bigger ROI in 30 days\n\nWhich sounds best? Let''s make this work."\n\n## Rescue Message #3: "No Results" Claim\n\n**Subject**: Let''s Fix This\n\n"Hey [Name],\n\nSaw your message about results. Let me dig in.\n\nCan we do a 30-min troubleshooting call tomorrow? I''ll personally review your setup and show you what needs to change.\n\nIf we can''t fix it, I''ll refund this month. Fair?"\n\n## Exercise\nWrite 3 churn rescue messages:\n1. For an inactive client\n2. For a price complaint\n3. For a "no results" claim\n\nAdd these to your playbook and share with your team.', 25)
  ON CONFLICT (module_id, lesson_index) DO NOTHING;

  -- Module 5: Delivery, Automation, Scaling
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 5, 'Delivery, Automation, Scaling', 'Fulfillment systems, workflows, partner scaling, and 30-day action plan.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title
  RETURNING id INTO v_mod5;

  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes) VALUES
    (v_mod5, 1, 'Onboarding Checklist (Day 1–7)', E'# Onboarding Checklist (Day 1–7)\n\n## Overview\nFast onboarding that produces quick wins and sets the tone for long-term retention.\n\n## Day 1-7 Checklist\n\n### Day 1: Welcome & Assets\n- [ ] Send welcome email\n- [ ] Request: logo, phone, hours, photos\n- [ ] Schedule kickoff call\n- [ ] Send onboarding calendar invite\n\n### Day 2-3: Setup\n- [ ] Create accounts/access\n- [ ] Configure missed call recovery\n- [ ] Set up tracking\n- [ ] Add to marketplace listing\n\n### Day 4-5: First Automation Live\n- [ ] Review automation live\n- [ ] First follow-up sent\n- [ ] Test missed call flow\n- [ ] Client receives test notification\n\n### Day 6: Training\n- [ ] 30-min training call\n- [ ] Walk through dashboard\n- [ ] Show how to view reports\n- [ ] Answer questions\n\n### Day 7: First Win Report\n- [ ] Send first week summary\n- [ ] Highlight quick wins\n- [ ] Set expectations for Week 2\n- [ ] Schedule Month 1 review\n\n## Exercise\nBuild your Day 1–7 checklist specific to your offer. Test with your next 3 clients and refine.', 25),
    
    (v_mod5, 2, 'Recurring Fulfillment Systems', E'# Recurring Fulfillment Systems\n\n## Overview\nMonthly task cadence + SOP basics so delivery is consistent and scalable.\n\n## Monthly Fulfillment Calendar\n\n### Week 1\n- Review last month''s performance\n- Update metrics dashboard\n- Send monthly report to clients\n- Schedule monthly meetings\n\n### Week 2\n- Optimize automations based on data\n- Add new features/updates\n- Handle support requests\n- Proactive outreach to quiet accounts\n\n### Week 3\n- Check system health\n- Review churn risk list\n- Prepare upsell offers\n- Content/template updates\n\n### Week 4\n- Monthly client meetings\n- Collect feedback\n- Plan next month improvements\n- Invoice reconciliation\n\n## SOP Template\n\n**Title**: [Task Name]\n\n**Frequency**: Daily/Weekly/Monthly\n\n**Owner**: [Person/Role]\n\n**Steps**:\n1. [Step 1]\n2. [Step 2]\n3. [Step 3]\n\n**Tools Needed**: [List]\n\n**Expected Time**: [X minutes]\n\n**Quality Check**: [How to verify done correctly]\n\n## Exercise\nWrite 5 SOP titles you need for consistent delivery:\n1. Client onboarding\n2. Monthly reporting\n3. Churn prevention check\n4. System optimization\n5. Upsell presentation', 20),
    
    (v_mod5, 3, 'Automation & CRM Workflows', E'# Automation & CRM Workflows\n\n## Overview\nAutomate follow-up, review requests, and missed-call recovery so your business runs without you.\n\n## Essential Workflows\n\n### Workflow 1: Lead to Appointment\n- **Trigger**: New lead captured\n- **Action 1**: Send welcome SMS (immediate)\n- **Action 2**: Send email with booking link (5 min later)\n- **Action 3**: Follow-up SMS if no response (24 hours)\n- **Action 4**: Phone call attempt (48 hours)\n- **Action 5**: Final SMS (72 hours)\n\n### Workflow 2: Missed Call Recovery\n- **Trigger**: Missed call detected\n- **Action 1**: Send SMS to customer (immediate): "Sorry we missed you! Book here: [link]"\n- **Action 2**: Notify client: "Missed call from [number]"\n- **Action 3**: Create CRM task for client\n- **Action 4**: Follow-up if no response (4 hours)\n\n### Workflow 3: Review Request\n- **Trigger**: Job marked complete\n- **Action 1**: Wait 24 hours\n- **Action 2**: Send review request SMS\n- **Action 3**: Send review request email\n- **Action 4**: Reminder if no response (3 days)\n- **Action 5**: Final reminder (7 days)\n\n### Workflow 4: Loyalty Program\n- **Trigger**: Customer visits X times\n- **Action 1**: Send reward notification\n- **Action 2**: Update loyalty points\n- **Action 3**: Send reward code\n- **Action 4**: Track redemption\n\n## Exercise\nMap your core workflow: lead → appointment → close → retain. Identify 5 touchpoints to automate.', 30),
    
    (v_mod5, 4, 'Partner/Reseller Scaling', E'# Partner/Reseller Scaling\n\n## Overview\nRecruit partners to sell your recurring offers and scale without hiring a sales team.\n\n## Partner Qualification Criteria\n\n1. **Access to target market**: Has existing relationships with your niche\n2. **Credibility**: Trusted advisor role (accountant, consultant, coach)\n3. **Motivated by passive income**: Wants recurring commissions\n4. **Non-competing**: Doesn''t offer same services\n5. **Professional**: Will represent your brand well\n\n## Commission Structure Example\n\n- **20% recurring** for life of client\n- **$100 bonus** on first sale\n- **Tier bonuses**: 5+ clients = 25%, 10+ = 30%\n- **Paid monthly** via direct deposit\n\n## Partner Invite Script\n\n"Hey [Name],\n\nQuick question: How many of your [niche] clients struggle with [problem]?\n\nWe have a done-for-you solution that solves [problem] for $297/mo, and I''d love to offer you 20% recurring commission on anyone you refer.\n\nMeaning: refer 10 clients = $600/mo passive income for you, ongoing.\n\nWant to see how it works? 15-minute call this week?"\n\n## Compliance Rules\n\n- Partners CANNOT modify pricing\n- Partners CANNOT make false claims\n- Partners MUST disclose commission relationship\n- Partners CANNOT sell to competitors without approval\n- Partners receive monthly performance reports\n\n## Exercise\n1. Write your partner invite pitch\n2. List 3 qualification criteria unique to your business\n3. Define your commission structure\n4. Identify 10 potential partners', 25),
    
    (v_mod5, 5, 'Your 30-Day Action Plan', E'# Your 30-Day Action Plan\n\n## Overview\nExecute weekly to close your first recurring clients and build momentum.\n\n## Week 1: Offer\n\n**Goal**: Finalize your recurring offer and pricing\n\n**Tasks**:\n- [ ] Choose your niche\n- [ ] Write your promise statement\n- [ ] Build your 3-tier pricing\n- [ ] Create deliverables checklist\n- [ ] Write your guarantee\n- [ ] Design your offer stack\n\n**Output**: One-page offer sheet\n\n## Week 2: Pipeline\n\n**Goal**: Build a list and start conversations\n\n**Tasks**:\n- [ ] Create list of 50 prospects\n- [ ] Write outreach message (3 versions)\n- [ ] Send 20 outreach messages\n- [ ] Book 5 discovery calls\n- [ ] Prepare discovery script\n\n**Output**: 5 scheduled appointments\n\n## Week 3: Close\n\n**Goal**: Present offers and close first clients\n\n**Tasks**:\n- [ ] Conduct 5 discovery calls\n- [ ] Present 3-tier pricing\n- [ ] Handle objections\n- [ ] Follow up on "think-about-its"\n- [ ] Close 2-3 clients\n\n**Output**: 2-3 signed clients\n\n## Week 4: Retain\n\n**Goal**: Deliver fast wins and prepare for scale\n\n**Tasks**:\n- [ ] Complete client onboarding\n- [ ] First automation live\n- [ ] Send first win report\n- [ ] Schedule Month 1 review\n- [ ] Document your SOPs\n- [ ] Plan Month 2 prospecting\n\n**Output**: Happy clients + refined process\n\n## Personal Action Plan Template\n\n**My 90-Day Revenue Goal**: $_______\n**Price Point**: $_______\n**Clients Needed**: _______\n**Weekly Close Target**: _______\n\n### Week 1 Focus:\n- [ ] Task 1\n- [ ] Task 2\n- [ ] Task 3\n\n### Week 2 Focus:\n- [ ] Task 1\n- [ ] Task 2\n- [ ] Task 3\n\n### Week 3 Focus:\n- [ ] Task 1\n- [ ] Task 2\n- [ ] Task 3\n\n### Week 4 Focus:\n- [ ] Task 1\n- [ ] Task 2\n- [ ] Task 3\n\n## Exercise\nFill in your personal 30-day plan. Share with an accountability partner and schedule weekly check-ins.', 20)
  ON CONFLICT (module_id, lesson_index) DO NOTHING;

END $$;