/*
  # Seed Blog Growth System - Partner Course (All 7 Modules)
  
  Creates all modules and lessons for the partner course:
  - Module 1: How Blogging Makes Money
  - Module 2: Choosing Your Blog Niche
  - Module 3: How to Write Blogs Businesses Will Pay For
  - Module 4: Pricing & Packaging Blog Services
  - Module 5: Getting Clients Through Local-Link
  - Module 6: Outreach (Optional but Powerful)
  - Module 7: Scaling Into an Agency or System
*/

DO $$
DECLARE
  v_course_id uuid;
  v_mod_id uuid;
BEGIN
  SELECT id INTO v_course_id FROM courses WHERE slug = 'blog-growth-partner';
  
  -- =====================================================
  -- MODULE 1: How Blogging Makes Money
  -- =====================================================
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 1, 'How Blogging Makes Money', 'Understand the blog writing business model and income potential.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
  RETURNING id INTO v_mod_id;
  
  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes)
  VALUES
    (v_mod_id, 1, 'Why businesses pay for blogs', E'# Why Businesses Pay for Blogs\n\n## The Local Business Problem\n\nMost local businesses:\n- Have no content strategy\n- Don''t understand SEO\n- Can''t write consistently\n- Don''t have time\n\n**They need you.**\n\n## What You Provide\n\n### Traffic\nBlogs bring Google traffic.\n\n### Leads\nContent converts visitors.\n\n### Authority\nContent builds trust.\n\n### Time\nYou do what they can''t.\n\n## The Business Case\n\nIf your blog generates 10 leads\nAnd client closes 2 sales\nAt $1,000 profit each\n\nYour $150 blog = $2,000 value\n\n**That''s a 13x ROI.**\n\nBusinesses will pay for that all day.\n\n**Action Step:** List 5 businesses in your area that need blogs.', 12),
    (v_mod_id, 2, 'Blog writing vs SEO agencies', E'# Blog Writing vs SEO Agencies\n\n## You''re Not Competing With Agencies\n\nAgencies charge $2,000-10,000/month.\nYou charge $300-900/month.\n\n## Different Markets\n\n**Agencies:**\n- Full technical SEO\n- Link building\n- Site audits\n- Large budgets\n\n**You:**\n- Content only\n- Simpler service\n- Affordable pricing\n- Small business focus\n\n## Your Advantage\n\n✅ More affordable\n✅ Faster turnaround\n✅ Personal service\n✅ Local expertise\n\n## Positioning\n\n"I''m a local blog writer, not an agency.\nI write SEO content that brings you leads.\nNo contracts, no complexity."\n\n**Action Step:** Write your positioning statement.', 10),
    (v_mod_id, 3, 'What businesses actually want', E'# What Businesses Actually Want\n\n## They Don''t Want\n\n❌ Technical jargon\n❌ Long contracts\n❌ Complex reports\n❌ Expensive packages\n\n## They Want\n\n✅ More phone calls\n✅ More customers\n✅ Higher Google ranking\n✅ Simple pricing\n✅ Fast results\n\n## The Conversation\n\n**They say:** "I need more leads"\n**You hear:** "I need blog content"\n\n**They say:** "I want to rank on Google"\n**You hear:** "I need consistent publishing"\n\n**They say:** "I don''t have time"\n**You hear:** "I''ll pay you to do it"\n\n## Your Value Prop\n\n"I write blogs that rank in Google and bring you customers. You approve the topics, I handle everything else."\n\n**Action Step:** Practice your pitch out loud 10 times.', 9),
    (v_mod_id, 4, 'Income examples & pricing models', E'# Income Examples & Pricing Models\n\n## Income Scenarios\n\n### Part-Time ($1,000-2,000/month)\n- 2-3 clients\n- 2-3 blogs each per month\n- $150/blog average\n- 10-15 hours/month\n\n### Side Hustle ($2,000-4,000/month)\n- 4-6 clients\n- 2-4 blogs each\n- 15-25 hours/month\n\n### Full-Time ($4,000-8,000/month)\n- 8-12 clients\n- Monthly retainers\n- 30-40 hours/month\n\n### Agency ($10,000+/month)\n- 15+ clients\n- Hire subcontractors\n- You manage, they write\n\n## Pricing Models\n\n**Per Blog:** $75-300\n**Monthly Package:** $300-900\n**Retainer:** $1,000-3,000\n\n## Real Example\n\n5 clients × $500/month = $2,500\nAt 20 hours/month = $125/hour\n\n**Action Step:** Choose your starting income goal.', 11);
  
  -- =====================================================
  -- MODULE 2: Choosing Your Blog Niche
  -- =====================================================
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 2, 'Choosing Your Blog Niche', 'Pick profitable niches and position yourself as a specialist.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
  RETURNING id INTO v_mod_id;
  
  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes)
  VALUES
    (v_mod_id, 1, 'Best local industries for blogging', E'# Best Local Industries for Blogging\n\n## High-Demand Industries\n\n### Home Services\n- HVAC, plumbing, electrical\n- High competition = need content\n- Ongoing service = repeat clients\n\n### Medical/Dental\n- Complex services need explanation\n- High-value customers\n- Can charge premium\n\n### Legal\n- Need to build trust\n- Technical topics\n- High-paying clients\n\n### Real Estate\n- Location-based content\n- Constant content need\n- Good budgets\n\n### Restaurants/Food\n- High volume needs\n- Lower budget (start here)\n- Easy to write\n\n### Beauty/Wellness\n- Med spas, salons\n- Image-conscious\n- Good budgets\n\n## Avoid\n\n❌ Retail (low margins)\n❌ E-commerce (different strategy)\n❌ B2B tech (too complex)\n\n**Action Step:** Pick 2-3 industries to target.', 13),
    (v_mod_id, 2, 'Picking 1-3 niches', E'# Picking 1-3 Niches\n\n## Why Specialize?\n\n- Easier to sell\n- Higher rates\n- Better results\n- Faster writing\n\n## Niche Selection Criteria\n\n### 1. Interest\nCan you write about this repeatedly?\n\n### 2. Local Demand\nAre there businesses in your area?\n\n### 3. Budget\nCan they afford $300-500/month?\n\n### 4. Content Need\nDo they actually need blogs?\n\n## The Sweet Spot\n\nPick niches where:\n✅ High local competition\n✅ Services need explanation\n✅ Customer research online\n✅ High transaction values\n\n## Example Combinations\n\n- Home services (HVAC, plumbing)\n- Medical (dental, med spa)\n- Professional services (law, accounting)\n\n**Action Step:** Commit to your 1-3 niches.', 10),
    (v_mod_id, 3, 'Positioning yourself as a specialist', E'# Positioning Yourself as a Specialist\n\n## Generic vs Specialist\n\n**Generic:**\n"I write blogs for businesses."\n\n**Specialist:**\n"I write SEO blogs for HVAC companies in the Pacific Northwest."\n\n## Benefits of Specializing\n\n### Easier Sales\n"I work with plumbers" > "I write for anyone"\n\n### Better Results\nYou understand the industry.\n\n### Higher Rates\nSpecialists charge more.\n\n### Faster Writing\nReuse research and frameworks.\n\n## Your Positioning Statement\n\n**Template:**\n"I help [niche] in [area] get more [result] through SEO blog content."\n\n**Examples:**\n- "I help HVAC companies in Texas get more service calls through SEO blogs."\n- "I help med spas rank #1 on Google with weekly blog content."\n- "I help law firms build authority with educational blog content."\n\n**Action Step:** Write and memorize your positioning statement.', 11);
  
  -- =====================================================
  -- MODULE 3: How to Write Blogs Businesses Will Pay For
  -- =====================================================
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 3, 'How to Write Blogs Businesses Will Pay For', 'Master the skill of writing blogs that deliver results for clients.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
  RETURNING id INTO v_mod_id;
  
  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes)
  VALUES
    (v_mod_id, 1, 'Writing for local SEO', E'# Writing for Local SEO\n\n## Local SEO Formula\n\n**[Service] + [Location] + [Intent]**\n\nExamples:\n- "Emergency plumbing in Seattle"\n- "Best HVAC repair in Phoenix"\n- "Affordable dentist near downtown Portland"\n\n## Structure Every Blog\n\n### Title\nInclude: service + location + benefit\n\n### Introduction\n- Acknowledge local context\n- Address pain point\n- Promise solution\n\n### Body\n- Include neighborhood names\n- Mention local landmarks\n- Address regional concerns\n- Use local examples\n\n### Conclusion\n- Clear CTA\n- Local contact info\n- Service area mention\n\n## Local Keywords\n\nUse:\n- City names\n- Neighborhood names\n- "Near me"\n- Regional terms\n\n**Action Step:** Write one local SEO blog following this formula.', 14),
    (v_mod_id, 2, 'Structuring service blogs', E'# Structuring Service Blogs\n\n## The Service Blog Template\n\n### Part 1: The Problem (100 words)\nDescribe the issue customers face.\n\n### Part 2: Why It Matters (200 words)\nExplain consequences of ignoring it.\n\n### Part 3: The Solution (400 words)\nDetail your client''s service approach.\n\n### Part 4: What to Expect (200 words)\nWalk through the process.\n\n### Part 5: Next Steps (100 words)\nClear CTA to contact business.\n\n## Example Structure\n\n**Title:** "Why Is My AC Blowing Warm Air?"\n\n**Intro:** It''s 95° and your AC is failing you.\n\n**Problem:** Common causes of warm air\n\n**Why It Matters:** Can lead to full system failure\n\n**Solution:** Diagnostic process\n\n**What to Expect:** Service call walkthrough\n\n**CTA:** "Schedule your diagnostic today"\n\n**Action Step:** Create 3 service blog outlines.', 12),
    (v_mod_id, 3, 'Writing fast without sacrificing quality', E'# Writing Fast Without Sacrificing Quality\n\n## The 45-Minute Blog\n\n**Minutes 0-10:** Research & outline\n**Minutes 10-35:** First draft\n**Minutes 35-45:** Edit & polish\n\n## Speed Writing Tips\n\n### 1. Use Templates\nStart with proven structures.\n\n### 2. Write Terrible First Drafts\nGet it done, then fix it.\n\n### 3. Batch Research\nResearch 4 topics at once.\n\n### 4. Use AI for Outlines\nThen write in your voice.\n\n### 5. Don''t Edit While Writing\nTwo separate phases.\n\n## Quality Checklist\n\n□ Clear headline\n□ Strong intro hook\n□ Scannable subheadings\n□ Short paragraphs\n□ Local context included\n□ Clear CTA\n□ Proofread\n\n## Practice Makes Perfect\n\nBlog #1: 2 hours\nBlog #10: 1 hour\nBlog #50: 45 minutes\n\n**Action Step:** Time yourself writing your next blog.', 10),
    (v_mod_id, 4, 'Using AI the right way', E'# Using AI the Right Way\n\n## AI Is Your Assistant, Not Your Replacement\n\n### Good Uses\n✅ Generate outlines\n✅ Research topics\n✅ Write first drafts\n✅ Headline ideas\n✅ Overcome writer''s block\n\n### Bad Uses\n❌ Copy-paste AI output\n❌ No human editing\n❌ Generic content\n❌ No local context\n\n## The Partner Method\n\n**Step 1:** AI generates draft\n**Step 2:** You add:\n- Local details\n- Client voice\n- Real examples\n- Personality\n- Industry expertise\n\n**Step 3:** Edit for readability\n**Step 4:** Add compelling CTA\n\n## Client Disclosure\n\n"I use AI to speed up research and drafting, but all content is heavily edited and customized for your business."\n\n**Be honest, be transparent.**\n\n**Action Step:** Write one blog using the Partner Method.', 11);
  
  -- =====================================================
  -- MODULE 4: Pricing & Packaging Blog Services
  -- =====================================================
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 4, 'Pricing & Packaging Blog Services', 'Set profitable prices and create packages clients say yes to.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
  RETURNING id INTO v_mod_id;
  
  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes)
  VALUES
    (v_mod_id, 1, 'Per-blog pricing vs monthly retainers', E'# Per-Blog Pricing vs Monthly Retainers\n\n## Two Models\n\n### Per-Blog Pricing\n**Structure:** $X per blog post\n**Pros:** Simple, low commitment\n**Cons:** Unpredictable income\n**Best for:** Starting out\n\n### Monthly Retainer\n**Structure:** $X/month for Y blogs\n**Pros:** Predictable income, client commitment\n**Cons:** Requires sales confidence\n**Best for:** Scaling\n\n## Pricing Comparison\n\n**Per-Blog:**\n- $100-150 per post\n- Client orders 2-4/month\n- Total: $200-600/month\n\n**Retainer:**\n- $400/month for 4 posts\n- Committed clients\n- More efficient for you\n\n## The Transition\n\nStart per-blog.\nAfter 2-3 months, offer:\n"Want to lock in this rate with a monthly package?"\n\n**Action Step:** Decide your starting model.', 10),
    (v_mod_id, 2, 'Entry-level vs premium packages', E'# Entry-Level vs Premium Packages\n\n## Three-Tier Pricing\n\n### Basic ($300/month)\n- 2 blogs per month\n- 600-800 words each\n- Basic keyword research\n- 1 round of revisions\n\n### Professional ($500/month)\n- 4 blogs per month\n- 800-1200 words each\n- Advanced keyword research\n- Graphics included\n- 2 rounds of revisions\n\n### Premium ($900/month)\n- 8 blogs per month\n- 1000-1500 words each\n- Full SEO optimization\n- Custom graphics\n- Distribution support\n- Unlimited revisions\n\n## Psychology\n\nMost clients choose middle option.\n\n## What to Include\n\n**Always:**\n- Content writing\n- Basic SEO\n- Revisions (1-2 rounds)\n\n**Upsells:**\n- Graphics ($25-50/post)\n- Rush delivery ($50+)\n- Social posts ($100/month)\n\n**Action Step:** Create your 3-tier pricing.', 12),
    (v_mod_id, 3, 'What to charge beginners vs experienced', E'# What to Charge: Beginners vs Experienced\n\n## Pricing Progression\n\n### Beginner (0-10 clients)\n**Per blog:** $75-100\n**Monthly:** $300-400\n\n**Why lower:**\n- Building portfolio\n- Learning process\n- Less confident\n\n### Intermediate (10-25 clients)\n**Per blog:** $100-150\n**Monthly:** $400-600\n\n**Why more:**\n- Proven results\n- Testimonials\n- Faster writing\n\n### Experienced (25+ clients)\n**Per blog:** $150-250\n**Monthly:** $600-1200\n\n**Why premium:**\n- Specialist positioning\n- Strong portfolio\n- High demand\n\n## When to Raise Rates\n\n✅ After 10 successful clients\n✅ When fully booked\n✅ When results proven\n✅ Every 6-12 months\n\n## Grandfathering\n\nOld clients keep old rates.\nNew clients pay new rates.\n\n**Action Step:** Set your current rate and next milestone.', 11),
    (v_mod_id, 4, 'Pricing calculator & package builder', E'# Pricing Calculator & Package Builder\n\n## Your Hourly Rate Goal\n\n**Formula:**\nTarget monthly income ÷ hours you''ll work = hourly rate\n\nExample:\n$3,000/month ÷ 60 hours = $50/hour\n\n## Per-Blog Pricing Formula\n\n**Time per blog:** 1-2 hours\n**Desired hourly rate:** $50-75\n**Price per blog:** $75-150\n\n## Monthly Package Calculator\n\n**Blogs/month × Rate × 0.85 = Package price**\n\n(0.85 = 15% bulk discount)\n\nExample:\n4 blogs × $125 × 0.85 = $425/month\n\n## Package Builder Template\n\n```\n[Package Name] - $[Price]/month\n\nIncludes:\n- X blog posts\n- X words each\n- Keyword research\n- [Other items]\n\nDeliverables:\n- Week 1: [Deliverable]\n- Week 2: [Deliverable]\n- Etc.\n\nRevisions: X rounds included\nCancellation: 30 days notice\n```\n\n**Action Step:** Build your first package offer.', 13);
  
  -- =====================================================
  -- MODULE 5: Getting Clients Through Local-Link
  -- =====================================================
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 5, 'Getting Clients Through Local-Link', 'Master the Local-Link marketplace and win high-paying jobs.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
  RETURNING id INTO v_mod_id;
  
  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes)
  VALUES
    (v_mod_id, 1, 'How Local-Link sends merchants to partners', E'# How Local-Link Sends Merchants to Partners\n\n## The Ecosystem\n\nMerchants take the Blog Course →\nRealize they need help →\nPost jobs in marketplace →\nYou apply and win the job\n\n## Built-In Demand\n\nLocal-Link creates the need.\nYou fulfill it.\n\n## Job Types\n\n### One-Time Projects\n- Single blog\n- Blog setup\n- Content audit\n\n### Monthly Retainers\n- 2-8 blogs/month\n- Ongoing partnerships\n- Predictable income\n\n### DFY Packages\n- Merchant bought $997 package\n- Includes 5 blogs written for them\n- Premium pay for you\n\n## Your Advantage\n\nCertified partners get:\n✅ Job alerts\n✅ Profile badge\n✅ Higher visibility\n✅ Client trust\n\n**Action Step:** Complete your partner profile.', 12),
    (v_mod_id, 2, 'Applying to blog jobs', E'# Applying to Blog Jobs\n\n## Winning Proposal Template\n\n### 1. Personal Greeting\n"Hi [Business Name],"\n\n### 2. Show Understanding\n"I see you''re looking for [specific need]. As a [your niche] specialist, I can help with that."\n\n### 3. Relevant Experience\n"I''ve written blogs for [similar businesses] that [achieved results]."\n\n### 4. Your Approach\n"Here''s how I''d approach your blog content: [brief overview]"\n\n### 5. Samples\n"Here are 2-3 relevant samples: [links]"\n\n### 6. Clear Pricing\n"My rate for this project: $[amount]\nTimeline: [days]"\n\n### 7. Easy Next Step\n"Happy to hop on a quick call to discuss. When works for you?"\n\n## What NOT to Do\n\n❌ Generic copy-paste proposals\n❌ No samples\n❌ Vague pricing\n❌ Over-promising\n❌ Too long (under 300 words)\n\n**Action Step:** Write your proposal template.', 10),
    (v_mod_id, 3, 'Building a strong partner profile', E'# Building a Strong Partner Profile\n\n## Profile Essentials\n\n### Professional Photo\nClear headshot, professional.\n\n### Compelling Bio\n"I help [niche] get more [result] through SEO blog content. [X] years experience, [Y] happy clients."\n\n### Portfolio Samples\nMinimum 5 samples:\n- Different industries\n- Different blog types\n- Best work only\n\n### Certifications\n- Local-Link Blog Partner badge\n- Any other relevant certs\n\n### Pricing\nClear, visible rates.\n\n### Testimonials\nAt least 3 client reviews.\n\n## Profile Optimization\n\n**Keywords to Include:**\n- SEO writing\n- Local business blogs\n- [Your niches]\n- [Your location]\n\n## Stand Out\n\n✅ Video introduction\n✅ Case study results\n✅ Quick response time\n✅ Clear communication\n\n**Action Step:** Optimize your profile today.', 11),
    (v_mod_id, 4, 'Getting repeat clients', E'# Getting Repeat Clients\n\n## The Repeat Client Formula\n\nGreat work + Good communication = Forever client\n\n## How to Earn Repeats\n\n### Deliver Early\nPromise 5 days, deliver in 4.\n\n### Exceed Expectations\nAdd extra value:\n- Suggest bonus topics\n- Include graphics\n- Optimize formatting\n\n### Communicate Proactively\n"Your blog will be ready Wednesday. Need anything else?"\n\n### Track Results\n"Your last blog got 500 views and 3 leads!"\n\n### Make It Easy to Continue\n"Want to lock in these 4 blogs for next month?"\n\n## Monthly Retainer Pitch\n\nAfter 2-3 one-off projects:\n\n"You''ve been happy with my work. Want to save 15% and lock in a monthly package? $400/month for 4 blogs, guaranteed slots."\n\n## Client Retention\n\n**Month 1:** Deliver great work\n**Month 2:** Show results\n**Month 3:** Propose retainer\n**Month 4+:** Long-term partnership\n\n**Action Step:** Draft your retainer pitch email.', 13);
  
  -- =====================================================
  -- MODULE 6: Outreach (Optional but Powerful)
  -- =====================================================
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 6, 'Outreach (Optional but Powerful)', 'Get clients outside the marketplace through proven outreach tactics.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
  RETURNING id INTO v_mod_id;
  
  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes)
  VALUES
    (v_mod_id, 1, 'Cold outreach scripts for blogs', E'# Cold Outreach Scripts for Blogs\n\n## Email Template #1: The SEO Gap\n\n**Subject:** Quick question about [Business Name]''s SEO\n\n**Body:**\nHi [Name],\n\nI was searching for "[their service] in [city]" and noticed [Business Name] isn''t ranking as high as you could be.\n\nI help [industry] businesses rank higher with consistent blog content. I''ve worked with [similar business] and helped them [result].\n\nWould you be open to a quick 10-minute call to discuss how blog content could help [Business Name] show up higher in Google?\n\n[Your Name]\n\n---\n\n## Email Template #2: The Value Add\n\n**Subject:** Free blog topic ideas for [Business Name]\n\n**Body:**\nHi [Name],\n\nI put together 10 blog topics that could help [Business Name] rank higher in [city]:\n\n[List 5 quick topics]\n\nI specialize in writing SEO blogs for [industry]. If you ever need help getting these written, let me know.\n\n[Your Name]\n\n---\n\n## When to Send\n\nTuesday-Thursday, 9 AM or 2 PM.\n\n**Action Step:** Send 5 outreach emails this week.', 10),
    (v_mod_id, 2, 'DM & email examples', E'# DM & Email Examples\n\n## LinkedIn DM Template\n\n"Hi [Name], I help [industry] businesses in [area] get more leads through SEO blog content. I noticed [Business Name] doesn''t have much blog content - is that something you''d ever consider? Happy to share some quick wins."\n\n## Instagram DM Template\n\n"Hey! Love your work at [Business Name]. Do you ever use blog content for SEO? I specialize in writing for [industry] and thought I could help. Mind if I send over a few topic ideas?"\n\n## Follow-Up Email (Day 3)\n\n**Subject:** Re: [Original subject]\n\n"Hi [Name], following up on my email from Tuesday. Would love to show you how blog content could bring [Business Name] more leads from Google. Free to chat this week?"\n\n## Follow-Up Email (Day 7)\n\n"Hi [Name], last time reaching out! If blog content isn''t a priority right now, totally understand. If it ever becomes one, you know where to find me. Good luck with [Business Name]!"\n\n**Action Step:** Set up follow-up reminders for your outreach.', 9),
    (v_mod_id, 3, 'Converting conversations into contracts', E'# Converting Conversations into Contracts\n\n## The Discovery Call\n\n### Question 1:\n"What are your main goals with content?"\n\n### Question 2:\n"What''s your biggest challenge with blogging right now?"\n\n### Question 3:\n"Have you tried blog content before?"\n\n### Question 4:\n"What does success look like for you?"\n\n### Question 5:\n"What''s your timeline and budget?"\n\n## Handling Objections\n\n**"It''s too expensive"**\n"Compared to what? Google Ads cost $3-10 per click. Blogs cost pennies per visitor."\n\n**"I don''t have time to manage this"**\n"That''s exactly why I''m here. You approve topics once a month, I handle everything else."\n\n**"How do I know it''ll work?"**\n"Here are results from [similar client]. Plus, we can start with just 2 blogs to test."\n\n## Closing\n\n"Based on what you''ve told me, I think [X blogs per month] makes sense. I can start next week if you''re ready. Sound good?"\n\n**Action Step:** Practice your discovery call questions.', 12);
  
  -- =====================================================
  -- MODULE 7: Scaling Into an Agency or System
  -- =====================================================
  INSERT INTO course_modules (course_id, module_index, title, description)
  VALUES (v_course_id, 7, 'Scaling Into an Agency or System', 'Grow beyond solo work into a scalable blog writing business.')
  ON CONFLICT (course_id, module_index) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
  RETURNING id INTO v_mod_id;
  
  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes)
  VALUES
    (v_mod_id, 1, 'Managing multiple clients', E'# Managing Multiple Clients\n\n## The 5-Client System\n\n**Client A:** 4 blogs/month (weeks 1-4)\n**Client B:** 4 blogs/month (weeks 1-4)\n**Client C:** 2 blogs/month (weeks 1-3)\n**Client D:** 2 blogs/month (weeks 2-4)\n**Client E:** 4 blogs/month (weeks 1-4)\n\nTotal: 16 blogs/month = ~24 hours\n\n## Batching Strategy\n\n**Monday:** Research all topics\n**Tuesday:** Write all drafts\n**Wednesday:** Edit all posts\n**Thursday:** Format and deliver\n**Friday:** Admin and client communication\n\n## Tools You Need\n\n### Project Management\n- Trello or Asana\n- Track all deadlines\n\n### Content Calendar\n- Google Sheets\n- Plan 30 days ahead\n\n### Templates\n- Standard structures\n- Reusable outlines\n\n### Time Tracking\n- Know your actual hours\n- Price accordingly\n\n**Action Step:** Set up your batching system.', 13),
    (v_mod_id, 2, 'Hiring subcontractors', E'# Hiring Subcontractors\n\n## When to Hire\n\n✅ Fully booked (can''t take more clients)\n✅ Making $4,000+/month\n✅ Have systems in place\n✅ Want to scale beyond your time\n\n## What to Pay\n\nYou charge: $150/blog\nYou pay writer: $50-75/blog\nYour margin: $75-100/blog\n\n## Finding Writers\n\n### Local-Link Marketplace\nHire other certified partners.\n\n### Job Boards\n- ProBlogger\n- Contently\n- Upwork (carefully)\n\n## Vetting Process\n\n1. Review portfolio\n2. Assign test blog ($50)\n3. Evaluate quality\n4. Start with 2-4 blogs/month\n5. Scale if good\n\n## Quality Control\n\n- You edit every piece\n- Your name on the work\n- Your reputation at stake\n\n## The Model\n\nYou: Client management, editing, strategy\nThem: Research, drafting\n\nYou manage 10 clients\nThey write the content\n\n**Action Step:** Calculate when you''ll need to hire.', 12),
    (v_mod_id, 3, 'Turning blog services into recurring income', E'# Turning Blog Services Into Recurring Income\n\n## The Retainer Model\n\n### Why Retainers Win\n\n✅ Predictable income\n✅ Client commitment\n✅ Less sales work\n✅ Relationship building\n✅ Better planning\n\n## Monthly Packages\n\n**Starter:** $400/month (2 blogs)\n**Growth:** $700/month (4 blogs)\n**Scale:** $1,200/month (8 blogs)\n\n## The Pitch\n\nAfter 2-3 successful one-off projects:\n\n"I''ve loved working with you. Want to make this a monthly thing? I can reserve [X] blogs per month for you at a discount. Plus, we can plan further ahead."\n\n## Contract Elements\n\n- Monthly fee\n- Number of blogs\n- Word count range\n- Revisions included\n- Cancellation terms (30 days)\n\n## Income Math\n\n5 retainer clients × $600/month = $3,000 recurring\n\nThat''s stable income you can count on.\n\n**Action Step:** Convert 2 clients to retainers this quarter.', 11);
    
  -- Add final congratulations message
  INSERT INTO course_lessons (module_id, lesson_index, title, content_md, video_duration_minutes)
  VALUES
    (v_mod_id, 4, 'Your path to blog income', E'# Your Path to Blog Income\n\n## 🎓 Congratulations!\n\nYou now have a complete roadmap to building a blog writing business.\n\n## What You''ve Learned\n\n✅ Why businesses pay for blogs\n✅ How to choose profitable niches\n✅ Writing blogs that get results\n✅ Pricing your services\n✅ Getting clients through Local-Link\n✅ Scaling beyond solo work\n\n## Your 30-Day Action Plan\n\n### Week 1\n- Complete your partner profile\n- Create 3 portfolio samples\n- Set your pricing\n\n### Week 2\n- Apply to 10 Local-Link jobs\n- Send 10 outreach emails\n- Land your first client\n\n### Week 3\n- Deliver exceptional work\n- Ask for testimonial\n- Apply to 10 more jobs\n\n### Week 4\n- Land 2-3 more clients\n- Set up batching system\n- Plan for $2,000/month\n\n## Income Milestones\n\n**Month 1-2:** $500-1,000 (2-3 clients)\n**Month 3-4:** $1,500-2,500 (4-6 clients)\n**Month 5-6:** $3,000-5,000 (8-10 clients)\n**Month 7-12:** $5,000-8,000 (scale or hire)\n\n## The Local-Link Advantage\n\nYou''re not building this alone.\n\n- Built-in client demand\n- Certified training\n- Marketplace support\n- Partner community\n\n## Next Steps\n\n1. **Complete your certification exam**\n2. **Build your portfolio** (even if unpaid at first)\n3. **Apply to your first 10 jobs**\n4. **Land your first paying client**\n5. **Deliver amazing work**\n6. **Rinse and repeat**\n\n## Final Thought\n\nThousands of local businesses need what you now know how to do.\n\nThey''ll pay you well for it.\n\nAll you have to do is start.\n\n**Go make it happen. 🚀**\n\n---\n\n## Need Help?\n\n- Join the Local-Link partner community\n- Connect with other blog partners\n- Get ongoing training and support\n\n**Welcome to the Local-Link Partner Family!**', 15)
  ON CONFLICT (module_id, lesson_index) DO UPDATE SET
    title = EXCLUDED.title,
    content_md = EXCLUDED.content_md;
    
END $$;
